// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdG6pvphC7Qqt6t-AbUoJ_NFbopmvhpyE',
    appId: '1:314273359365:android:5b92cabc3f9cd37296de6c',
    messagingSenderId: '314273359365',
    projectId: 'hotel-parking-system',
    storageBucket: 'hotel-parking-system.appspot.com',
    databaseURL: 'https://hotel-parking-system-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdG6pvphC7Qqt6t-AbUoJ_NFbopmvhpyE',
    appId: '1:314273359365:android:5b92cabc3f9cd37296de6c',
    messagingSenderId: '314273359365',
    projectId: 'hotel-parking-system',
    storageBucket: 'hotel-parking-system.appspot.com',
    databaseURL: 'https://hotel-parking-system-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCglTV2ghlCAypKf10SE1JwK20qwuoLXYA',
    appId: '1:314273359365:ios:e83da9fdaa9b35d696de6c',
    messagingSenderId: '314273359365',
    projectId: 'hotel-parking-system',
    storageBucket: 'hotel-parking-system.appspot.com',
    iosBundleId: 'com.example.epark',
    databaseURL: 'https://hotel-parking-system-default-rtdb.firebaseio.com',
  );
}
